# -*- coding: utf-8 -*-
"""Final Project .

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKUTYlk29CqRPPQoIohD_ac8UQPTGSxq
"""

import kagglehub
path = kagglehub.dataset_download("gauthamvijayaraj/customer-purchase-behavior-dataset-e-commerce")
print("Path to dataset files:", path)

!pip install kaggle
from google.colab import files
files.upload()

import pandas as pd
import numpy as np

df = pd.read_csv('customerData_500k.csv')
df.head()

df.info()

df.info()

df.shape

df.columns

df.isnull().sum()

df = df.dropna()

df['Age'] = df['Age'].fillna(df['Age'].mean())

df['AnnualIncome'] = df['AnnualIncome'].fillna(df['AnnualIncome'].mode()[0])

df = df.drop_duplicates()

df['Region'] = df['Region'].str.title()

df['Gender'] = df['Gender'].replace({'M': 'Male', 'F': 'Female'})

df['ProductCategory'] = df['ProductCategory'].astype('category')

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['ProductCategory'] = le.fit_transform(df['ProductCategory'])

df = pd.get_dummies(df, columns=['ProductCategory'], drop_first=True)

from sklearn.preprocessing import StandardScaler, MinMaxScaler

scaler = StandardScaler()
df[['Age', 'AnnualIncome']] = scaler.fit_transform(df[['Age', 'AnnualIncome']])

df.to_csv('cleaned_data.csv', index=False)
print("Cleaned dataset saved successfully!")